version: 2
models:
  - name: stg_aw__store
    description: >
      Standardizes the store data, ensuring consistency and validating key constraints,
      such as unique identifiers and relationships with business entities.
    columns:
      - name: business_entity_id
        description: >
          Identifier for the business entity associated with the store.
        tests:
          - unique
          - not_null
      - name: sales_person_id
        description: >
          Identifier for the salesperson related to the store.
        tests:
          - not_null
      - name: store_name
        description: >
          Name of the store.
        tests:
          - not_null
      - name: demographics
        description: >
          Demographic details about the store.
      - name: rowguid
        description: >
          Unique identifier for each record.
      - name: modified_date
        description: >
          The date the record was last modified.
      - name: _sdc_extracted_at
        description: >
          Extraction timestamp from the source system.
      - name: _sdc_received_at
        description: >
          Timestamp indicating when the data was received.
      - name: _sdc_batched_at
        description: >
          Timestamp indicating when the batch was processed.
      - name: _sdc_deleted_at
        description: >
          Timestamp indicating when the data was marked for deletion.
      - name: _sdc_sequence
        description: >
          Sequence number for data extraction.
      - name: _sdc_table_version
        description: >
          Version of the source table.
      - name: _sdc_sync_started_at
        description: >
          Timestamp when synchronization started.

  - name: stg_aw__customer
    description: >
      Standardizes the customer data, ensuring consistency and validating key constraints, 
      such as unique identifiers and relationships with stores and sales territories. No foreign keys are enforced in the staging tables.
    columns:
      - name: customer_id
        description: >
          Unique identifier for each customer.
        tests:
          - unique
          - not_null
      - name: person_id
        description: >
          Identifier for the person associated with the customer.
      - name: store_id
        description: >
          Identifier for the store related to the customer.
      - name: territory_id
        description: >
          Identifier for the sales territory related to the customer.
      - name: rowguid
        description: >
          Unique identifier for each record.
      - name: modified_date
        description: >
          The date the record was last modified.
      - name: _sdc_extracted_at
        description: >
          Extraction timestamp from the source system.
      - name: _sdc_received_at
        description: >
          Timestamp indicating when the data was received.
      - name: _sdc_batched_at
        description: >
          Timestamp indicating when the batch was processed.
      - name: _sdc_deleted_at
        description: >
          Timestamp indicating when the data was marked for deletion.
      - name: _sdc_sequence
        description: >
          Sequence number for data extraction.
      - name: _sdc_table_version
        description: >
          Version of the source table.
      - name: _sdc_sync_started_at
        description: >
          Timestamp when synchronization started.

  - name: stg_aw__salespersonquotahistory
    description: >
      Standardizes the salesperson quota history data, ensuring consistency and validating key constraints and relationships. No foreign keys are enforced in the staging tables.
    columns:
      - name: business_entity_id
        description: >
          Identifier for the business entity related to the quota history.
      - name: quota_date
        description: >
          The date when the sales quota was set.
      - name: sales_quota
        description: >
          The sales quota amount.
      - name: rowguid
        description: >
          Unique identifier for each record.
      - name: modified_date
        description: >
          The date the record was last modified.
      - name: _sdc_extracted_at
        description: >
          Extraction timestamp from the source system.
      - name: _sdc_received_at
        description: >
          Timestamp indicating when the data was received.
      - name: _sdc_batched_at
        description: >
          Timestamp indicating when the batch was processed.
      - name: _sdc_deleted_at
        description: >
          Timestamp indicating when the data was marked for deletion.
      - name: _sdc_sequence
        description: >
          Sequence number for data extraction.
      - name: _sdc_table_version
        description: >
          Version of the source table.
      - name: _sdc_sync_started_at
        description: >
          Timestamp when synchronization started.

  - name: stg_aw__salesperson
    description: >
      Standardizes the salesperson data, ensuring consistency and validating key constraints, such as relationships to employees and sales territories. No foreign keys are enforced in the staging tables.
    columns:
      - name: business_entity_id
        description: >
          Identifier for the business entity related to the salesperson.
      - name: territory_id
        description: >
          Identifier for the sales territory related to the salesperson.
      - name: sales_quota
        description: >
          Projected yearly sales quota.
      - name: bonus
        description: >
          Bonus due if quota is met.
      - name: commission_pct
        description: >
          Commission percentage per sale.
      - name: sales_year_to_end
        description: >
          Year-to-date sales.
      - name: sales_last_year
        description: >
          Sales total from the previous year.
      - name: rowguid
        description: >
          Unique identifier for each record.
      - name: modified_date
        description: >
          The date the record was last modified.
      - name: _sdc_extracted_at
        description: >
          Extraction timestamp from the source system.
      - name: _sdc_received_at
        description: >
          Timestamp indicating when the data was received.
      - name: _sdc_batched_at
        description: >
          Timestamp indicating when the batch was processed.
      - name: _sdc_deleted_at
        description: >
          Timestamp indicating when the data was marked for deletion.
      - name: _sdc_sequence
        description: >
          Sequence number for data extraction.
      - name: _sdc_table_version
        description: >
          Version of the source table.
      - name: _sdc_sync_started_at
        description: >
          Timestamp when synchronization started.

  - name: stg_aw__salesterritory
    description: >
      Standardizes the sales territory data, ensuring consistency and validating key constraints, such as relationships with states and territories. No foreign keys are enforced in the staging tables.
    columns:
      - name: territory_id
        description: >
          Unique identifier for each sales territory.
        tests:
          - unique
          - not_null
      - name: territory_name
        description: >
          Name of the sales territory.
      - name: countryregion_code
        description: >
          Identifier for the country region related to the sales territory.
      - name: territory_group
        description: >
          Group associated with the sales territory.
      - name: sales_year_to_end
        description: >
          Year-to-date sales total.
      - name: sales_last_year
        description: >
          Sales total from the previous year.
      - name: cost_year_to_end
        description: >
          Year-to-date cost.
      - name: cost_last_year
        description: >
          Cost total from the previous year.
      - name: rowguid
        description: >
          Unique identifier for each record.
      - name: modified_date
        description: >
          The date the record was last modified.
      - name: _sdc_extracted_at
        description: >
          Extraction timestamp from the source system.
      - name: _sdc_received_at
        description: >
          Timestamp indicating when the data was received.
      - name: _sdc_batched_at
        description: >
          Timestamp indicating when the batch was processed.
      - name: _sdc_deleted_at
        description: >
          Timestamp indicating when the data was marked for deletion.
      - name: _sdc_sequence
        description: >
          Sequence number for data extraction.
      - name: _sdc_table_version
        description: >
          Version of the source table.
      - name: _sdc_sync_started_at
        description: >
          Timestamp when synchronization started.

  - name: stg_aw__specialoffer
    description: >
      Standardizes the special offer data, ensuring consistency and validating key constraints, such as discounts and offer validity. No foreign keys are enforced in the staging tables.
    columns:
      - name: special_offer_id
        description: >
          Unique identifier for each special offer.
        tests:
          - unique
          - not_null
      - name: description_discount
        description: >
          Description of the special offer.
      - name: discount_pct
        description: >
          Discount percentage applied to the special offer.
      - name: type_discount
        description: >
          Type/category of the special offer.
      - name: category
        description: >
          Category of the special offer.
      - name: start_date
        description: >
          Start date of the special offer.
      - name: end_date
        description: >
          End date of the special offer.
      - name: min_quantity
        description: >
          Minimum quantity required for the special offer.
      - name: max_quantity
        description: >
          Maximum quantity allowed for the special offer.
      - name: rowguid
        description: >
          Unique identifier for each record.
      - name: modified_date
        description: >
          The date the record was last modified.
      - name: _sdc_extracted_at
        description: >
          Extraction timestamp from the source system.
      - name: _sdc_received_at
        description: >
          Timestamp indicating when the data was received.
      - name: _sdc_batched_at
        description: >
          Timestamp indicating when the batch was processed.
      - name: _sdc_deleted_at
        description: >
          Timestamp indicating when the data was marked for deletion.
      - name: _sdc_sequence
        description: >
          Sequence number for data extraction.
      - name: _sdc_table_version
        description: >
          Version of the source table.
      - name: _sdc_sync_started_at
        description: >
          Timestamp when synchronization started.
